"""baseline current schema

Revision ID: f638c5b72379
Revises: 
Create Date: 2026-07-30 02:12:18.891688

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f638c5b72379'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankroll_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('game', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('odds', sa.Integer(), nullable=True),
    sa.Column('wager', sa.Float(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('stat_type', sa.String(), nullable=True),
    sa.Column('win_probability', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_entry_id', sa.Integer(), nullable=True),
    sa.Column('entry_mode', sa.String(), nullable=True),
    sa.Column('payout_type', sa.String(), nullable=True),
    sa.Column('payout_table_snapshot', sa.Text(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=False),
    sa.Column('average_edge', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('wager', sa.Float(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('payout_type', sa.String(), nullable=False),
    sa.Column('payout_table_snapshot', sa.Text(), nullable=False),
    sa.Column('expected_return', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('potential_payout', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('entry_mode', sa.String(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('recommended_by_app', sa.Boolean(), nullable=False),
    sa.Column('audit_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(), nullable=False),
    sa.Column('player_identity_id', sa.Integer(), nullable=True),
    sa.Column('player_provider', sa.String(), nullable=True),
    sa.Column('provider_player_id', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('stat', sa.String(), nullable=False),
    sa.Column('game', sa.String(), nullable=True),
    sa.Column('game_date', sa.String(), nullable=True),
    sa.Column('actual', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_player_stats_player'), 'final_player_stats', ['player'], unique=False)
    op.create_index(op.f('ix_final_player_stats_player_identity_id'), 'final_player_stats', ['player_identity_id'], unique=False)
    op.create_index(op.f('ix_final_player_stats_sport'), 'final_player_stats', ['sport'], unique=False)
    op.create_index(op.f('ix_final_player_stats_stat'), 'final_player_stats', ['stat'], unique=False)
    op.create_table('player_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('canonical_key', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('current_team', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key', 'sport', name='uq_player_identity_key_sport')
    )
    op.create_index(op.f('ix_player_identities_canonical_key'), 'player_identities', ['canonical_key'], unique=False)
    op.create_index(op.f('ix_player_identities_sport'), 'player_identities', ['sport'], unique=False)
    op.create_table('prediction_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('entry_prop_id', sa.Integer(), nullable=False),
    sa.Column('independent_market_key', sa.String(), nullable=False),
    sa.Column('offer_key', sa.String(), nullable=False),
    sa.Column('player_identity_id', sa.Integer(), nullable=True),
    sa.Column('player', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('stat', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('game', sa.String(), nullable=True),
    sa.Column('game_time', sa.String(), nullable=True),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('projection', sa.Float(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('projection_source', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('line_offer_type', sa.String(), nullable=True),
    sa.Column('feature_as_of', sa.String(), nullable=True),
    sa.Column('feature_snapshot', sa.Text(), nullable=True),
    sa.Column('payout_snapshot', sa.Text(), nullable=True),
    sa.Column('legacy_quarantined', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('outcome_source', sa.String(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_prop_id', name='uq_prediction_record_entry_prop')
    )
    op.create_index(op.f('ix_prediction_records_entry_id'), 'prediction_records', ['entry_id'], unique=False)
    op.create_index(op.f('ix_prediction_records_entry_prop_id'), 'prediction_records', ['entry_prop_id'], unique=False)
    op.create_index(op.f('ix_prediction_records_independent_market_key'), 'prediction_records', ['independent_market_key'], unique=False)
    op.create_index(op.f('ix_prediction_records_offer_key'), 'prediction_records', ['offer_key'], unique=False)
    op.create_index(op.f('ix_prediction_records_platform'), 'prediction_records', ['platform'], unique=False)
    op.create_index(op.f('ix_prediction_records_player_identity_id'), 'prediction_records', ['player_identity_id'], unique=False)
    op.create_index(op.f('ix_prediction_records_sport'), 'prediction_records', ['sport'], unique=False)
    op.create_index(op.f('ix_prediction_records_stat'), 'prediction_records', ['stat'], unique=False)
    op.create_table('prop_line_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(), nullable=False),
    sa.Column('stat', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('game', sa.String(), nullable=True),
    sa.Column('game_time', sa.String(), nullable=True),
    sa.Column('line_offer_type', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_line_history_player'), 'prop_line_history', ['player'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('settlement_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('entry_prop_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('matched_identity_id', sa.Integer(), nullable=True),
    sa.Column('requested_player', sa.String(), nullable=False),
    sa.Column('matched_player', sa.String(), nullable=False),
    sa.Column('requested_game', sa.String(), nullable=False),
    sa.Column('matched_game', sa.String(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_prop_id', 'status', 'provider', 'reason_code', name='uq_settlement_audit_attempt')
    )
    op.create_index(op.f('ix_settlement_audits_entry_id'), 'settlement_audits', ['entry_id'], unique=False)
    op.create_index(op.f('ix_settlement_audits_entry_prop_id'), 'settlement_audits', ['entry_prop_id'], unique=False)
    op.create_index(op.f('ix_settlement_audits_reason_code'), 'settlement_audits', ['reason_code'], unique=False)
    op.create_index(op.f('ix_settlement_audits_status'), 'settlement_audits', ['status'], unique=False)
    op.create_table('entry_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('player_identity_id', sa.Integer(), nullable=True),
    sa.Column('player_provider', sa.String(), nullable=True),
    sa.Column('provider_player_id', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('stat', sa.String(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('projection', sa.Float(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('game', sa.String(), nullable=True),
    sa.Column('game_time', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('baseline_line', sa.Float(), nullable=True),
    sa.Column('standard_line', sa.Float(), nullable=True),
    sa.Column('line_offer_type', sa.String(), nullable=True),
    sa.Column('adjusted_line', sa.Boolean(), nullable=True),
    sa.Column('is_discounted_line', sa.Boolean(), nullable=True),
    sa.Column('is_premium_line', sa.Boolean(), nullable=True),
    sa.Column('line_discount', sa.Float(), nullable=True),
    sa.Column('projection_source', sa.String(), nullable=True),
    sa.Column('auto_projected', sa.Boolean(), nullable=True),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('final_result', sa.String(), nullable=True),
    sa.Column('final_source', sa.String(), nullable=True),
    sa.Column('final_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_player_id', sa.String(), nullable=True),
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.Column('alias_key', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['player_identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id', 'provider', 'alias_key', name='uq_player_alias_identity_provider_name'),
    sa.UniqueConstraint('provider', 'provider_player_id', name='uq_player_alias_provider_id')
    )
    op.create_index(op.f('ix_player_aliases_alias_key'), 'player_aliases', ['alias_key'], unique=False)
    op.create_index(op.f('ix_player_aliases_identity_id'), 'player_aliases', ['identity_id'], unique=False)
    op.create_index(op.f('ix_player_aliases_provider'), 'player_aliases', ['provider'], unique=False)
    op.create_index(op.f('ix_player_aliases_provider_player_id'), 'player_aliases', ['provider_player_id'], unique=False)
    op.create_index(op.f('ix_player_aliases_sport'), 'player_aliases', ['sport'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_aliases_sport'), table_name='player_aliases')
    op.drop_index(op.f('ix_player_aliases_provider_player_id'), table_name='player_aliases')
    op.drop_index(op.f('ix_player_aliases_provider'), table_name='player_aliases')
    op.drop_index(op.f('ix_player_aliases_identity_id'), table_name='player_aliases')
    op.drop_index(op.f('ix_player_aliases_alias_key'), table_name='player_aliases')
    op.drop_table('player_aliases')
    op.drop_table('entry_props')
    op.drop_index(op.f('ix_settlement_audits_status'), table_name='settlement_audits')
    op.drop_index(op.f('ix_settlement_audits_reason_code'), table_name='settlement_audits')
    op.drop_index(op.f('ix_settlement_audits_entry_prop_id'), table_name='settlement_audits')
    op.drop_index(op.f('ix_settlement_audits_entry_id'), table_name='settlement_audits')
    op.drop_table('settlement_audits')
    op.drop_table('settings')
    op.drop_index(op.f('ix_prop_line_history_player'), table_name='prop_line_history')
    op.drop_table('prop_line_history')
    op.drop_index(op.f('ix_prediction_records_stat'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_sport'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_player_identity_id'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_platform'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_offer_key'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_independent_market_key'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_entry_prop_id'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_entry_id'), table_name='prediction_records')
    op.drop_table('prediction_records')
    op.drop_index(op.f('ix_player_identities_sport'), table_name='player_identities')
    op.drop_index(op.f('ix_player_identities_canonical_key'), table_name='player_identities')
    op.drop_table('player_identities')
    op.drop_index(op.f('ix_final_player_stats_stat'), table_name='final_player_stats')
    op.drop_index(op.f('ix_final_player_stats_sport'), table_name='final_player_stats')
    op.drop_index(op.f('ix_final_player_stats_player_identity_id'), table_name='final_player_stats')
    op.drop_index(op.f('ix_final_player_stats_player'), table_name='final_player_stats')
    op.drop_table('final_player_stats')
    op.drop_table('entries')
    op.drop_table('bets')
    op.drop_table('bankroll_transactions')
    # ### end Alembic commands ###
